In [2]:
import numpy as np
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [3]:
print('Rank of t: ', t.ndim) # 몇차원인지 출력
print('Shape of t: ', t.shape)

Rank of t:  1
Shape of t:  (7,)


In [4]:
print('t[0] t[1] t[2] =', t[0], t[1], t[-1])

t[0] t[1] t[2] = 0.0 1.0 6.0


In [6]:
import torch
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [13]:
t = torch.FloatTensor([[1.,2.,3.],
                      [4.,5.,6.],
                      [7.,8.,9.]]
                     )

In [17]:
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([2,2])
m1 + m2

tensor([[5., 5.]])

In [20]:
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3])
m1 + m2

tensor([[4., 5.]])

In [22]:
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3],[4]])
m1+m2

tensor([[4., 5.],
        [5., 6.]])

In [271]:
m1 = torch.FloatTensor([[1,2], [3,4]])
m2 = torch.FloatTensor([[1],[2]])
print('Shape of Matrix 1: ', m1.shape)
print('Shape of Matrix 2: ', m2.shape)
print(m1.matmul(m2))
#print(m2.matmul(m1))
m1.size()


Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


torch.Size([2, 2])

In [32]:
t = torch.FloatTensor([1, 2])
print(t.mean())
print(t.mean(dim=0))

tensor(1.5000)
tensor(1.5000)


In [36]:
t = torch.FloatTensor([[1, 2], [3,4 ]])
print(t)
print(t.shape)
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1).shape)

tensor([[1., 2.],
        [3., 4.]])
torch.Size([2, 2])
tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
torch.Size([2])


In [43]:
t = torch.FloatTensor([[[1, 2], [3,4 ]],[[5, 6], [7,8 ]]])
print(t)
print(t.shape)
print(t.sum())
print('\n')
print(t.sum(dim=0))
print('\n')
print(t.sum(dim=1))
print('\n')
print(t.sum(dim=-1).shape)
print('\n')
print(t.sum(dim=2))

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])
torch.Size([2, 2, 2])
tensor(36.)


tensor([[ 6.,  8.],
        [10., 12.]])


tensor([[ 4.,  6.],
        [12., 14.]])


torch.Size([2, 2])


tensor([[ 3.,  7.],
        [11., 15.]])


In [49]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.max())
print(t.max(dim=0))
print('Max : ', t.max(dim=0)[0])
print('ArgMax : ', t.max(dim=0)[1])

t.max(dim=0)[0] + t.max(dim=0)[1]

tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max :  tensor([3., 4.])
ArgMax :  tensor([1, 1])


tensor([4., 5.])

4) 뷰(View) 원소의 수를 유지하면서 텐서의 크기 변경

In [51]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


-1 : 첫번째 차원은 사용자가 잘 모르겠으니 파이토치가 알아서 해주고 3은 2번째 차원의 길이를 3으로 하겠다. <br>
3 : 두번쨰 차원길이는 3을 갖도록 하겠다. (?, 3)으로 만들겠다.

In [55]:
print(ft.view(-1, 3))
print(ft.view(-1, 6))
print(ft.view([-1,1,3]))
print(ft.view([-1,1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]])
tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


5) 스퀴즈(Squeeze) 1인 차원을 제거

In [68]:
ft = torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape)
print(ft.squeeze())
print(ft.squeeze().shape)
#torch.Size([8])

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
tensor([0., 1., 2.])
torch.Size([3])


6) 언스퀴즈(Unsqueeze) 특정 위치에 1인 차원 추가

In [71]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

print(ft.unsqueeze(0)) # 인덱스는 0부터 시작하므로 첫번째 차원을 의미
print(ft.unsqueeze(0).shape)
ft1= ft.unsqueeze(0)
print(ft1.unsqueeze(0))
print(ft1.unsqueeze(0).shape)

torch.Size([3])
tensor([[0., 1., 2.]])
torch.Size([1, 3])
tensor([[[0., 1., 2.]]])
torch.Size([1, 1, 3])


In [72]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [73]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [75]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [76]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


In [79]:
x = torch.FloatTensor([[1,2], [3,4]])
y = torch.FloatTensor([[5, 6], [7, 8]])
print(torch.cat([x, y], dim = 0))
print(torch.cat([x, y], dim = 1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


9) 스택킹(Stacking)

In [84]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])
print(torch.stack([x, y, z]))
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)]))
print(torch.stack([x, y, z], dim = 1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


10) ones_like와 zeros_lie - 0 으로 채워진 텐서와 1로 채워진 텐서

In [85]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [87]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


11) In-place Operation(덮어쓰기 연산)


In [90]:
x = torch.FloatTensor([[1, 2], [3, 4]])
print(x.mul(2))
print(x)

# mul_ 을 쓰면 덮어씀
print(x.mul_(2))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


선형회귀

In [92]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
torch.manual_seed(1)

In [93]:
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])
print(x_train)
print(x_train.shape)


tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [96]:
# 가중치 W를 0으로 초기화하고 학습을 통해 값이 변경되는 변수임을 명시함
W = torch.zeros(1, requires_grad = True) #requirese_grad = True : 학습을 통해 변경되는 변수
print(W)
b = torch.zeros(1, requires_grad = True)
print(b)

tensor([0.], requires_grad=True)
tensor([0.], requires_grad=True)


In [98]:
hypothesis = x_train * W + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [102]:
cost = torch.mean((hypothesis - y_train) ** 2)
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


In [103]:
optimizer = optim.SGD([W, b], lr = 0.01)

# gradient를 0으로 초기화
optimizer.zero_grad()

# 비용 함수를 미분하여 gradient 계산
cost.backward()

# W와 b를 업데이트
optimizer.step()

In [107]:
nb_epochs = 2000
for epoch in range(nb_epochs + 1):
    
    # H(x) 계산
    hypothesis = x_train * W + b
    
    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)
    
    #cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost:{:.6f}'.format(
             epoch, nb_epochs, W.item(), b.item(), cost.item()))
        #print(W)
        #print(W.item())

Epoch    0/2000 W: 2.000, b: 0.000 Cost:0.000000
Epoch  100/2000 W: 2.000, b: 0.000 Cost:0.000000
Epoch  200/2000 W: 2.000, b: 0.000 Cost:0.000000
Epoch  300/2000 W: 2.000, b: 0.000 Cost:0.000000
Epoch  400/2000 W: 2.000, b: 0.000 Cost:0.000000
Epoch  500/2000 W: 2.000, b: 0.000 Cost:0.000000
Epoch  600/2000 W: 2.000, b: 0.000 Cost:0.000000
Epoch  700/2000 W: 2.000, b: 0.000 Cost:0.000000
Epoch  800/2000 W: 2.000, b: 0.000 Cost:0.000000
Epoch  900/2000 W: 2.000, b: 0.000 Cost:0.000000
Epoch 1000/2000 W: 2.000, b: 0.000 Cost:0.000000
Epoch 1100/2000 W: 2.000, b: 0.000 Cost:0.000000
Epoch 1200/2000 W: 2.000, b: 0.000 Cost:0.000000
Epoch 1300/2000 W: 2.000, b: 0.000 Cost:0.000000
Epoch 1400/2000 W: 2.000, b: 0.000 Cost:0.000000
Epoch 1500/2000 W: 2.000, b: 0.000 Cost:0.000000
Epoch 1600/2000 W: 2.000, b: 0.000 Cost:0.000000
Epoch 1700/2000 W: 2.000, b: 0.000 Cost:0.000000
Epoch 1800/2000 W: 2.000, b: 0.000 Cost:0.000000
Epoch 1900/2000 W: 2.000, b: 0.000 Cost:0.000000
Epoch 2000/2000 W: 2

In [110]:
import torch
w = torch.tensor(2.0, requires_grad = True)
nb_epochs = 20
for epoch in range(nb_epochs + 1):
    z = 2*w
    z.backward()
    print('수식을 w로 미분한 값 : {}'.format(w.grad))

수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 4.0
수식을 w로 미분한 값 : 6.0
수식을 w로 미분한 값 : 8.0
수식을 w로 미분한 값 : 10.0
수식을 w로 미분한 값 : 12.0
수식을 w로 미분한 값 : 14.0
수식을 w로 미분한 값 : 16.0
수식을 w로 미분한 값 : 18.0
수식을 w로 미분한 값 : 20.0
수식을 w로 미분한 값 : 22.0
수식을 w로 미분한 값 : 24.0
수식을 w로 미분한 값 : 26.0
수식을 w로 미분한 값 : 28.0
수식을 w로 미분한 값 : 30.0
수식을 w로 미분한 값 : 32.0
수식을 w로 미분한 값 : 34.0
수식을 w로 미분한 값 : 36.0
수식을 w로 미분한 값 : 38.0
수식을 w로 미분한 값 : 40.0
수식을 w로 미분한 값 : 42.0


In [112]:


w = torch.tensor(2.0, requires_grad = True)
y = w**2
z = 2*y + 5
z.backward()
print('수식을 w로 미분한 값 : {}'.format(w.grad))


수식을 w로 미분한 값 : 8.0


In [126]:
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  80], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

print(x_train.shape)
print(y_train.shape)

W = torch.zeros((3, 1), requires_grad=True)
W = torch.zeros(x_train.shape[1], requires_grad=True)
b = torch.zeros(1, requires_grad=True)
hypothesis = x_train.matmul(W) + b

optimizer = optim.SGD([W, b], lr=1e-5)

nb_epochs = 20
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    # 편향 b는 브로드 캐스팅되어 각 샘플에 더해집니다.
    hypothesis = x_train.matmul(W) + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(
        epoch, nb_epochs, hypothesis.squeeze().detach(), cost.item()
    
    ))
   # print(epoch)


torch.Size([5, 3])
torch.Size([5, 1])
Epoch    0/20 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch    1/20 hypothesis: tensor([65.7645, 79.0259, 75.0170, 84.7907, 60.2843]) Cost: 10108.092773
Epoch    2/20 hypothesis: tensor([103.0480, 123.8282, 117.5473, 132.8605,  94.4618]) Cost: 3823.312256
Epoch    3/20 hypothesis: tensor([124.1848, 149.2279, 141.6598, 160.1122, 113.8384]) Cost: 1803.305664
Epoch    4/20 hypothesis: tensor([136.1674, 163.6278, 155.3308, 175.5614, 124.8240]) Cost: 1154.044189
Epoch    5/20 hypothesis: tensor([142.9602, 171.7915, 163.0821, 184.3195, 131.0524]) Cost: 945.354248
Epoch    6/20 hypothesis: tensor([146.8108, 176.4197, 167.4774, 189.2841, 134.5839]) Cost: 878.267822
Epoch    7/20 hypothesis: tensor([148.9934, 179.0436, 169.9700, 192.0980, 136.5863]) Cost: 856.695557
Epoch    8/20 hypothesis: tensor([150.2303, 180.5311, 171.3840, 193.6927, 137.7220]) Cost: 849.751404
Epoch    9/20 hypothesis: tensor([150.9311, 181.3744, 172.1864, 194.5963

In [127]:
# channel : 3, height : 4, width : 2로 가정합니다.
A = torch.randint(10, (3, 4, 2))
print(A)

tensor([[[5, 9],
         [4, 8],
         [3, 3],
         [1, 1]],

        [[9, 2],
         [8, 9],
         [6, 3],
         [3, 0]],

        [[2, 1],
         [2, 6],
         [0, 3],
         [6, 4]]])


In [134]:
# 0번째 축(channel) 기준 argmax w/o Keepdim
print(torch.argmax(A, dim=0))
print(torch.argmax(A, dim=0).shape)


tensor([[1, 0],
        [1, 1],
        [1, 0],
        [2, 2]])
torch.Size([4, 2])


In [133]:
print(torch.argmax(A, dim=0, keepdim = True))
print(torch.argmax(A, dim = 0, keepdim = True).shape)

tensor([[[1, 0],
         [1, 1],
         [1, 0],
         [2, 2]]])
torch.Size([1, 4, 2])


In [136]:
print(torch.argmax(A, dim=1))
print(torch.argmax(A, dim=1).shape)

tensor([[0, 0],
        [0, 1],
        [3, 1]])
torch.Size([3, 2])


In [138]:
print(torch.argmax(A, dim=1, keepdim = True))
print(torch.argmax(A, dim=1, keepdim = True).shape)

tensor([[[0, 0]],

        [[0, 1]],

        [[3, 1]]])
torch.Size([3, 1, 2])


In [139]:
print(torch.argmax(A, dim=2))
print(torch.argmax(A, dim=2).shape)

tensor([[1, 1, 0, 0],
        [0, 1, 0, 0],
        [0, 1, 1, 0]])
torch.Size([3, 4])


In [141]:
print(torch.argmax(A, dim=2, keepdim=True))
print(torch.argmax(A, dim=2, keepdim=True).shape)

tensor([[[1],
         [1],
         [0],
         [0]],

        [[0],
         [1],
         [0],
         [0]],

        [[0],
         [1],
         [1],
         [0]]])
torch.Size([3, 4, 1])


In [145]:
a = [[0.0034, 0.0029, 0.0057, 0.0040],
          [0.0036, 0.0026, 0.0041, 0.0037],
          [0.0043, 0.0007, 0.0021, 0.0019]]
a = torch.FloatTensor(a)
print(a)
torch.mean(a)

tensor([[0.0034, 0.0029, 0.0057, 0.0040],
        [0.0036, 0.0026, 0.0041, 0.0037],
        [0.0043, 0.0007, 0.0021, 0.0019]])


tensor(0.0032)

In [151]:
print(torch.mean(a, dim = 0))
print(torch.mean(a, dim = 0).shape)
print(torch.mean(a, dim = 0, keepdim=True))
print(torch.mean(a, dim = 0, keepdim=True).shape)


tensor([0.0038, 0.0021, 0.0040, 0.0032])
torch.Size([4])
tensor([[0.0038, 0.0021, 0.0040, 0.0032]])
torch.Size([1, 4])


In [212]:
import torch

x = torch.arange(16).view(2,2,2,2).float()
print(x)
print('\n')
x_mean = torch.mean(x, axis = [0], keepdim = True)
print(x_mean.shape)
print('\n')

x_mean = torch.mean(x, axis = [1], keepdim = True)
print(x_mean.shape)
print('\n')
x_mean = torch.mean(x, axis = [2], keepdim = True)
print(x_mean.shape)
print('\n')
x_mean = torch.mean(x, axis = [3], keepdim = True)
print(x_mean.shape)
print('\n')


x_mean = torch.mean(x, axis = [0,1], keepdim = True)
print(x_mean.shape)
print('\n')




x_mean = torch.mean(x, axis = [1,2], keepdim = True)
print(x_mean.shape)
print('\n')


print(x_mean)

tensor([[[[ 0.,  1.],
          [ 2.,  3.]],

         [[ 4.,  5.],
          [ 6.,  7.]]],


        [[[ 8.,  9.],
          [10., 11.]],

         [[12., 13.],
          [14., 15.]]]])


torch.Size([1, 2, 2, 2])


torch.Size([2, 1, 2, 2])


torch.Size([2, 2, 1, 2])


torch.Size([2, 2, 2, 1])


torch.Size([1, 1, 2, 2])


torch.Size([2, 1, 1, 2])


tensor([[[[ 3.,  4.]]],


        [[[11., 12.]]]])


In [156]:
x_mean = torch.mean(x, axis = [2,3], keepdim = True)

TypeError: mean() received an invalid combination of arguments - got (Tensor, keepdim=bool), but expected one of:
 * (Tensor input, *, torch.dtype dtype)
 * (Tensor input, tuple of names dim, bool keepdim, *, torch.dtype dtype, Tensor out)
 * (Tensor input, tuple of ints dim, bool keepdim, *, torch.dtype dtype, Tensor out)


In [157]:
x = torch.tensor([1,2,3])
x.repeat(4,2)


tensor([[1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3]])

In [158]:
x.repeat(4,2,1).size()

torch.Size([4, 2, 3])

In [159]:
x.repeat(4,2,1)

tensor([[[1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3]]])

In [170]:
x = torch.tensor([[1],[2],[3]])
print(x)
print(x.size())
print(x.expand(3,4))


tensor([[1],
        [2],
        [3]])
torch.Size([3, 1])
tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]])


In [189]:
x = torch.empty(5,1,4,2)
x

tensor([[[[0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00],
          [0.0000e+00, 2.6661e-09],
          [1.8788e+31, 1.7220e+22]]],


        [[[1.9152e+23, 1.6783e-07],
          [1.0027e-11, 3.4155e-06],
          [2.1122e+20, 4.2245e-05],
          [4.1946e+21, 3.3733e-06]]],


        [[[2.6879e-06, 1.7283e-04],
          [3.1369e+27, 7.0800e+31],
          [3.1095e-18, 7.7052e+31],
          [1.9447e+31, 2.0558e+32]]],


        [[[1.8755e+28, 3.1093e-18],
          [1.9421e+31, 2.7491e+20],
          [2.3078e-12, 1.8179e+31],
          [1.8524e+28, 1.9152e+23]]],


        [[[1.6783e-07, 1.0027e-11],
          [3.4155e-06, 2.1122e+20],
          [4.2245e-05, 4.1946e+21],
          [3.3733e-06, 2.6879e-06]]]])

tensor([[[[1.0010e-38],
          [4.2246e-39],
          [1.0286e-38],
          [1.0653e-38]],

         [[2.9445e-05],
          [2.9445e-05],
          [2.9445e-05],
          [2.9445e-05]],

         [[1.0010e-38],
          [4.2246e-39],
          [1.0286e-38],
          [1.0653e-38]]],


        [[[1.0194e-38],
          [8.4490e-39],
          [1.0469e-38],
          [9.3674e-39]],

         [[2.9445e-05],
          [2.9445e-05],
          [2.9445e-05],
          [2.9445e-05]],

         [[1.0194e-38],
          [8.4490e-39],
          [1.0469e-38],
          [9.3674e-39]]],


        [[[9.9184e-39],
          [8.7245e-39],
          [9.2755e-39],
          [8.9082e-39]],

         [[2.9445e-05],
          [2.9445e-05],
          [2.9445e-05],
          [2.9445e-05]],

         [[9.9184e-39],
          [8.7245e-39],
          [9.2755e-39],
          [8.9082e-39]]],


        [[[9.9184e-39],
          [8.4490e-39],
          [9.6429e-39],
          [1.0653e-38]],

         [[2.9

torch.Size([5, 3, 4, 1])

In [190]:

x=torch.empty(1)
y=torch.empty(3,1,7)
print(x+y)
(x+y).size()
torch.Size([3, 1, 7])


tensor([[[nan, nan, nan, nan, nan, nan, nan]],

        [[nan, nan, nan, nan, nan, nan, nan]],

        [[nan, nan, nan, nan, nan, nan, nan]]])


torch.Size([3, 1, 7])

In [ ]:
x=torch.empty(5,1,4,1)
y=torch.empty(  3,1,1)
print(x+y)
(x+y).size()
torch.Size([5, 3, 4, 1])


In [210]:

x=torch.empty(5,1,4,1)
y=torch.empty(  3,2,1)
(x+y).size()

RuntimeError: The size of tensor a (4) must match the size of tensor b (2) at non-singleton dimension 2

In [214]:
x = torch.FloatTensor([[1,2], [3,4]])
y = torch.FloatTensor([[5, 6], [7, 8]])
print(torch.cat([x, y], dim = 0))
print(torch.cat([x, y], dim = 1))



tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [239]:
x = torch.arange(256).view(16,1,4,4).float()
a = 16
b = 1
c = 4
d = 4
y = torch.arange(a*b*c*d).view(a,b,c,d,).float()
#print(x)
print('\n')
x_mean = torch.mean(x, axis = [1], keepdim = True)
x_mean.shape
print(torch.cat([x, y], 1).shape)



torch.Size([16, 2, 4, 4])


In [240]:
result = isinstance("It's string", str) 
print(result) 

True


In [246]:
def get_batchsize(resolution):
    R = int(np.log2(resolution))
    if R < 7:
        bs = 32 / 2**(max(0, R-4))
    else:
        bs = 8 / 2**(min(2, R-7))
    return int(bs)


batchsize_map = {2**R: get_batchsize(2**R) for R in range(2, 11)}
batchsize_map

{4: 32, 8: 32, 16: 32, 32: 16, 64: 8, 128: 8, 256: 4, 512: 2, 1024: 2}

In [248]:
import argparse

parser = argparse.ArgumentParser(description='사용법 테스트')
parser.add_argument('--target', required=True, help = '어느것을 요구하나')
parser.add_argument('--env', required=False, default = 'dev', help = '실행환경은 머냐')

args = parser.parse_args()
print(args.target)
print(args.env)

usage: ipykernel_launcher.py [-h] --target TARGET [--env ENV]
ipykernel_launcher.py: error: the following arguments are required: --target


SystemExit: 2

C:\Users\jeonghwan.kim\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3445: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [249]:
import argparse

parser = argparse.ArgumentParser(description='Process some integers.')
parser.add_argument('integers', metavar='N', type=int, nargs='+',
                    help='an integer for the accumulator')
parser.add_argument('--sum', dest='accumulate', action='store_const',
                    const=sum, default=max,
                    help='sum the integers (default: find the max)')

args = parser.parse_args()
print(args.accumulate(args.integers))


usage: ipykernel_launcher.py [-h] [--sum] N [N ...]
ipykernel_launcher.py: error: argument N: invalid int value: 'C:\\Users\\jeonghwan.kim\\AppData\\Roaming\\jupyter\\runtime\\kernel-ff8a0f8b-f2bb-4279-bf1d-1f4ce6fbf942.json'
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "C:\Users\jeonghwan.kim\anaconda3\lib\argparse.py", line 2409, in _get_value
    result = type_func(arg_string)
ValueError: invalid literal for int() with base 10: 'C:\\Users\\jeonghwan.kim\\AppData\\Roaming\\jupyter\\runtime\\kernel-ff8a0f8b-f2bb-4279-bf1d-1f4ce6fbf942.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jeonghwan.kim\anaconda3\lib\argparse.py", line 1787, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\Users\jeonghwan.kim\anaconda3\lib\argparse.py", line 1996, in _parse_known_args
    stop_index = consume_positionals(start_index)
  File "C:\Users\jeonghwan.kim\anaconda3\lib\argparse.py", line 1952, in consume_positionals
    take_action(action, args)
  File "C:\Users\jeonghwan.kim\anaconda3\lib\argparse.py", line 1845, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "C:

TypeError: object of type 'NoneType' has no len()

In [250]:
import argparse
parser = argparse.ArgumentParser()
parser.parse_args()

usage: ipykernel_launcher.py [-h]
ipykernel_launcher.py: error: unrecognized arguments: -f C:\Users\jeonghwan.kim\AppData\Roaming\jupyter\runtime\kernel-ff8a0f8b-f2bb-4279-bf1d-1f4ce6fbf942.json


SystemExit: 2

In [255]:
import numpy as np
x = np.mod(5, 2)
x

1

In [259]:
class father():  # 부모 클래스
    def __init__(self, who):
        self.who = who
 
    def handsome(self):
        print("{}를 닮아 잘생겼다".format(self.who))
 
class sister(father):  # 자식클래스(부모클래스) 아빠매소드를 상속받겠다
    def __init__(self, who, where):
        super().__init__(who)
        self.where = where
 
    def choice(self):
        print("{} 말이야".format(self.where))
 
    def handsome(self):
        super().handsome()
        self.choice()

girl = sister("아빠", "얼굴")
girl.handsome()

아빠를 닮아 잘생겼다
얼굴 말이야


In [260]:
import tensorflow as tf
tf.get_default_session

AttributeError: module 'tensorflow' has no attribute 'get_default_session'

In [262]:
a = 3.0
for i in range(a):
    print(i)

TypeError: 'float' object cannot be interpreted as an integer

In [265]:
rows_map = {64: 16, 32: 16, 16: 8, 8: 4, 4: 2, 2: 2}
rows_map[32]

16

In [282]:
import numpy as np
from torch.autograd import Variable
z = np.random.normal(0,1,[10, 20])
a = Variable(torch.from_numpy(z), requires_grad=False).cuda().float()
a
a.size()

torch.Size([10, 20])